name: Push Container to Heroku

on: 
  push:
    branches:
      - master

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - uses: actions/setup-node@v1
      with:
        node-version: '12.x'
    - name: Login to Heroku Container registry
      env: 
        HEROKU_API_KEY: ${{ secrets.HEROKU_API_KEY }}
      run: heroku container:login
    - run: |
        heroku git:remote -a fullstackcicd
        git push heroku master 
    - uses: akhileshns/heroku-deploy@master
      with:
        heroku_api_key: ${{ secrets.HEROKU_API_KEY }}
        heroku_app_name: "fullstackcicd"
        heroku_email: "tampv@tmh-techlab.vn"


      
