name: Deploy

on:
  push:
    branches:
      - master

jobs:
  build:
    runs-on: ubuntu-20.04
    steps:
      - uses: actions/checkout@v2
      - name: Login to Heroku Container registry
        env: 
          HEROKU_API_KEY: ${{ secrets.HEROKU_API_KEY }}
        run: heroku container:login 

      - uses: akhileshns/heroku-deploy@v3.8.8
        with:
          heroku_email: "tampv@tmh-techlab.vn"
          heroku_api_key: ${{secrets.HEROKU_API_KEY}}
          heroku_app_name: cicdapps
          branch: HEAD
          useforce: false
          dynamicFiles: false
          healthcheck: "https://cicdapps.herokuapp.com/health"
          checkstring: "ok"
          rollbackonhealthcheckfailed: true


      
